apiVersion: apps/v1
kind: Deployment
metadata:
  name: footprintLogger
  labels:
    app: footprintLogger
spec:
  replicas: 2
  selector:
    matchLabels:
      app: footprintLogger
  template:
    metadata:
      labels:
        app: footprintLogger
    spec:
      containers:
        - name: footprintLogger-container
          image: us.icr.io/sn-labs-thabisorants/giftapp #remember to change the image
          ports:
            - containerPort: 3060
      imagePullSecrets:
        - name: icr # change this too

---
apiVersion: v1
kind: Service
metadata:
  name: footprint-logger-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3060
      protocol: TCP
  selector:
    app: footprintLogger
