version: "3.9"

services:
  app:
    build: .
    container_name: footprint-logger-backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start
